### ISSUE TITLE
The bookmarks plugin is polluting the .leo file with inappropriate data

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1247]
## Background

Fairly recently temporary data of no long-term interest such as node marks were moved out of the .leo file an into the cache.  This eliminated node marking differences from git diffs.

I believe the bookmark plugin data shown in the git diff below is temporary data of interest only to the bookmark plugin and is of no long-term interest.  Hence, it should not pollute the .leo file.  It should be moved to the cache.
```
-<t tx="bob.20180827145653.1">blist = [
+<t tx="bob.20180827145653.1" __bookmarks="7d7100580700000069735f6475706571014930300a732e">blist = [
```
I don't fully understand what __bookmarks= signifies or what causes it.  But it seems that the bookmarks plugin inserts this data in the node that has focus when the .leo file is closed.

I have the bookmarks plugin enabled, but I have never used it.  Maybe someday I'll learn how to use it.

## Test Systems
```
Leo Log Window
Leo 6.0-b2-devel, devel branch, build aaba312c4f
2019-06-26 09:19:58 -0500
Python 3.6.8, PyQt version 5.11.1
linux
import-jupyter-notebook requires nbformat package
```

**Comment by edreamleo** [comment]
@SegundoBob I agree.

**Comment by tbnorth** [comment]
"I have the bookmarks plugin enabled, but I have never used it. Maybe someday I'll learn how to use it."

It seems odd that this would happen if you aren't using the plugin.  Could the changes for the docks UI be instantiating bookmarks on some arbitrary node when there isn't a bookmarks node specified for the file?

**Comment by edreamleo** [comment]
On Thu, Jul 11, 2019 at 8:46 PM Terry Brown <notifications@github.com>
wrote:

> "I have the bookmarks plugin enabled, but I have never used it. Maybe
> someday I'll learn how to use it."
>
> It seems odd that this would happen if you aren't using the plugin. Could
> the changes for the docks UI be instantiating bookmarks on some arbitrary
> node when there isn't a bookmarks node specified for the file?
>

Thanks for this. I've changed the label from "Enhancement" to "Bug".  It
should be fixed for 6.0.

Edward

**Comment by edreamleo** [comment]
Rev 69f4b39 contains a possible fix.  The top-level init function contained this code:

```python
f g.app.config.getBool('bookmarks-grab-dblclick'):
    g.registerHandler('headdclick1', lambda t,k: cmd_open_bookmark(k))
```
I've changed this to:
```python
f g.app.config.getBool('bookmarks-grab-dblclick', default=False):
    g.registerHandler('headdclick1', lambda t,k: cmd_open_bookmark(k))
```
This makes it clear that this setting should not be on by default.

Also, I've added `@bool 'bookmarks-grab-dblclick = False` to leoSettings.leo.

I'll continue investigating.

**Comment by edreamleo** [comment]
I believe I've found the problem.  BookMarkDisplay.__init__ sets c._bookmarks = self.  This will "pollute" the .leo file.  The immediate workaround is to disable bookmarks.py.

**Comment by edreamleo** [comment]
I am going to close this issue.  Terry, it's up to you whether c._bookmarks should be changed to, say, c.db ['bookmarks'].  That is, it's up to you whether these data are "essential" or not.

**Comment by tbnorth** [comment]
> I believe I've found the problem. `BookMarkDisplay.__init__` sets c._bookmarks = self. This will "pollute" the .leo file. The immediate workaround is to disable bookmarks.py.

How does setting ivar c._bookmarks (one underscore) result in uA p.v.__bookmarks (two underscores) being set on some node in the outline?  The c instance isn't searched for unknown ivars on save?

The __bookmarks dict seems to just be being used to tag duplicate bookmarks for display purposes and can probably be moved to p.v.__bookmarks.  But I still don't think the code should be being triggered in the first place.

**Comment by edreamleo** [comment]
On Fri, Jul 12, 2019 at 8:02 AM Terry Brown <notifications@github.com>
wrote:

> How does setting ivar c._bookmarks (one underscore) result in uA
> p.v.__bookmarks (two underscores) being set on some node in the outline?
> The c instance isn't searched for unknown ivars on save?
>
Good questions.  My theory is probably wrong.

> The __bookmarks dict seems to just be being used to tag duplicate
> bookmarks for display purposes and can probably be moved to
> p.v.__bookmarks. But I still don't think the code should be being triggered
> in the first place.
>
BookMarkDisplay.__init__ is called by onCreate.

Edward

**Comment by edreamleo** [comment]
The show-all-uas command shows that many (all?) nodes have a ua as follows:
```
{
  __bookmarks:{
      is_dupe:False
    }
}
```

So perhaps my theory was correct after all.

**Comment by edreamleo** [comment]
So the recommended workaround is to disable bookmarks.py and use the clear-all-uas command.

**Comment by tbnorth** [comment]
> So perhaps my theory was correct after all.

Only when it explains the relationship between c._bookmarks and p.v.u['__bookmarks'] ;-)

I just installed Leo but I have no idea how to start the Bookmarks plugin, show-bookmarks from Alt-X or the Plugins menu does nothing and Window -> Window Layout -> Freelayout Context Menu just reports an AttributeError.

I'm missing something?  Otherwise these plugins (Bookmarks, Todo, etc.) seem DOA in the docks UI.

**Comment by edreamleo** [comment]
The following experiment seems to clear the bookmarks plugin of responsibility:

- enable the bookmarks plugin
- clear-all-uas
- save the file
- reload Leo
- show-all-uas (nothing is shown)

This is quite a mystery.  I'd like to resolve this and #1245 for 6.0.

**Comment by edreamleo** [comment]
The bookmarks mystery is almost certainly solved.  The __bookmarks ua arises if and only if one clicks on a bookmark.  That is, the file is "polluted" only if one actually uses the bookmarks plugin and clicks in the bookmarks pane.

There is no mystery about what happens next.  fc.putDescendentVnodeUas adds a field to the corresponding `@<file>` node.  Its helpers are fc.createUaList and fc.pickle.
