### ISSUE TITLE
Tree abbreviation placeholders in headlines not working as expected

### ISSUE THREAD

**Issue by xgid** [leo-editor/leo-editor#438]
Placeholders (items to be filled in) are not working in the expected way **when the placeholders are present at the headlines** of any of the nodes of a tree abbreviation.

Let's take this tree abbreviation example to make it more clear:
```text
mdfile;;
	@clean <|filename|>.md
		""" The body here """
		Description: <|summary|>
```

The tree abbreviation **mdfile;;** has one only node with a placeholder (`<|filename|>`) in its headline and a second placeholder (`<|summary|>`) inside its body. 

When I insert the abbreviation (by typing "**mdfile;;**"), the node is correctly created and the cursor is positioned in the `<|summary|>` placeholder and I can type the field value. But when I press `,,` the behaviour is as if I had already filled the last field. At this point typing two commas does nothing more.
So the placeholder in the headline (`<|filename|>`) is not recognized as such and is never asked to be filled in.

**Comment by JohnLunzer** [comment]
I think Terry would have to comment on this. My first inclination is that placeholders were not meant to be used in headlines. This may end up being a feature request, rather than a bug.

**Comment by edreamleo** [comment]
@JohnLunzer No. It is a bug.

**Comment by tbnorth** [comment]
Edward extended abbreviations to cover trees, I'm not familiar worth that part of the code. 

On March 14, 2017 7:41:51 AM CDT, John Lunzer <notifications@github.com> wrote:
>I think Terry would have to comment on this. My first inclination is
>that placeholders were not meant to be used in headlines. This may end
>up being a feature request, rather than a bug.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/leo-editor/leo-editor/issues/438#issuecomment-286409116

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edreamleo** [comment]
Fixed at e4e2fb8 in the abbrev branch.  All tests pass.

**Comment by xgid** [comment]
Hi Eduard, thanks for addressing this so fast.

I've just downloaded the abbrev branch and tried the new code, but it hurts me having to say that it is not yet fully working.

I've tried with a new tree abbreviation like this one:
```text
mdfile;;
	@<|type|> <|filename|>.md
		""" The body here """
		Description: <|summary|>
```

and the `<|type|>` placeholder is now correctly being asked for and filled in, but pressing `,,` after that, takes me directly to the position zero of the body (line 0, col. 0) and the `<|filename|>` placeholder being automatically converted to the text "filename". Pressing `,,` again, takes me to the `<|summary|>` placeholder and I can correctly fill it in. A final `,,` press does nothing more.

I've also tried with another tree abbreviation that has two nodes, one child of the other, with several placeholders in both headlines and the behaviour seems to be the same: only the first placeholder in the first node is asked for, the rest are "ignored" (well, in fact not truly ignored but, again, their "name" is converted to plain text).

Please, tell me if you need any further info.

**Comment by edreamleo** [comment]
> @<|type|> <|filename|>.md

The existing code allows only one substitution per headline.  Clearly, the kind of headline substitutions in your example are reasonable.  For sure you don't want `@clean` in your tree. I'll see what I can do, but again, no guarantees.  This is messy code.

**Comment by edreamleo** [comment]
Fixed at 097a01 in master.

**Comment by xgid** [comment]
Hi Eduard, 

I've tried again with the new master branch and it is now **nearly** working! :sweat:
Now all placeholders are being "detected" and asked for, in headlines and in the bodies. But in headlines, weirdly **only the last placeholder can be actually filled in**. The previous ones in the headline are reverted back to their original "name" as soon as I press the `,,` after filling them in.

To make it more clear: in the example above, after inserting the tree abbreviation and changing the value of the first placeholder to "clean", the second one to "test" and the third to "a simple test" the resulting tree is this one:
```text
@type test.md
	""" The body here """
	Description: a simple test
```
See the first placeholder being reverted to "type" again, instead of "clean".

If the code is quite difficult as you said, I may try to help in debugging and even fixing it. How could I show debug traces of the code being run?

**Comment by xgid** [comment]
PD: I don't know how to reopen de issue. Can I do it?

**Comment by edreamleo** [comment]
Your original example works for me.  Are you sure your template is correct?

**Comment by xgid** [comment]
I've reviewed the template and it is exactly as shown above: just one node with 2 placeholders in the headline and another placeholder in the body. Nothing more. How could my template be wrong?

My environment configuration is this one:
```
Leo Log Window
Leo 5.4, build 20170316064048, Thu Mar 16 06:40:48 CDT 2017
Git repo info: branch = master, commit = bad90a98649f
Python 3.5.2, PyQt version 5.6.0
Windows 10 AMD64 (build 10.0.14393) SP0
```

I attach my myLeoSettings.leo file so you can review it. In fact it's quite small.
[myLeoSettings.zip](https://github.com/leo-editor/leo-editor/files/848476/myLeoSettings.zip)

Anyway, how could I enable debug traces to be able to send you a more detailed log?

**Comment by xgid** [comment]
OK, I've enabled the "--debug" flag at the command line and this is what is shown when inserting the tree abbreviation:
```text
** isPython3: True
Leo 5.4, build 20170316064048, Thu Mar 16 06:40:48 CDT 2017
Git repo info: branch = master, commit = bad90a98649f
Python 3.5.2, PyQt version 5.6.0
Windows 10 AMD64 (build 10.0.14393) SP0
selectChapterForPosition *** Tests main main redraw,selectPosition
selectChapterForPosition *** selecting main chapter
selectChapterForPosition *** Tests main main redraw,selectPosition
selectChapterForPosition *** selecting main chapter
selectChapterForPosition *** Tests main main redraw,selectPosition
selectChapterForPosition *** selecting main chapter
selectChapterForPosition *** mdfile;; main main getLeoOutlineFromClipboard,selectPosition
selectChapterForPosition *** selecting main chapter
selectChapterForPosition *** mdfile;; main main pasteOutline,selectPosition
selectChapterForPosition *** selecting main chapter
selectChapterForPosition *** mdfile;; main main paste_tree,selectPosition
selectChapterForPosition *** selecting main chapter
selectChapterForPosition *** mdfile;; main main redraw,selectPosition
selectChapterForPosition *** selecting main chapter
selectChapterForPosition *** Tests main main redraw,selectPosition
selectChapterForPosition *** selecting main chapter
selectChapterForPosition *** @type <|filename|>.md main main redraw,selectPosition
selectChapterForPosition *** selecting main chapter
selectChapterForPosition *** @type filename.md main main redraw,selectPosition
selectChapterForPosition *** selecting main chapter
wrote recent file: C:\Users\sysadmin\.leo\.leoRecentFiles.txt
selectChapterForPosition *** @type test.md main main redraw,selectPosition
selectChapterForPosition *** selecting main chapter
```

Are there any more detailed traces I could activate?

**Comment by xgid** [comment]
Well, I've been able to debug the code a little bit and I've found this behaviour:
When the execution of `AbbrevCommandsClass.expandAbbrev` finishes for the first placeholder in the headline, the main loop returns the control to the GUI. Then I insert the new value for the field and immediately I press ",," to go to the next placeholder.

At this moment, a new event is fired which triggers a new call to `AbbrevCommandsClass.expandAbbrev`, but at that point the value of p.h has not been yet updated to the new contents I have just typed in the GUI. So at this point, a new expansion is started and when the code gets to `AbbrevCommandsClass.find_place_holder` and a new placeholder is found in the headline, the following code at abbrevCommands.py, lines 393 to 402:
```python
    new_s, i, j = self.next_place(s, offset=0)
    if i is not None:
        if trace: g.trace('found in headline', p.h)
        p.h = new_s
        c.redraw(p)
        c.editHeadline()
        w = c.edit_widget(p)
        if trace: g.trace(w)
        w.setSelectionRange(i, j, insert=j)
        return True
```
sets the value of p.h **back to the previous one (before my changes!)**, although this time with the new placeholder (the second one) replaced from "<|filename|>" to just "filename".
Then the following redraw and some other calls seem to (re)set the text in the widget to the wrong value.

In the other hand, when no more placeholders are found in the headline (i.e. we have already filled in the last one in that headline), the above call to `self.next_place` sets **i** to `None`, so p.h is no longer overwritten and seems to survive the new event loop.

I don't know if this explanation may be of any help.

**Comment by edreamleo** [comment]
@xgid The code above seems correct to me.  In particular, the code
```python
s = p.h
new_s, i, j = self.next_place(s, offset=0)
 if i is not None:
        p.h = new_s
        ...
```
*does* update p.h to the _new_ value of s, new_s. The code works for me on Windows 10.

**Comment by edreamleo** [comment]
I'm not going to delay Leo 5.5b1 for this. I'll be happy to fix further bugs here, but at present I don't see what the bug is.

**Comment by xgid** [comment]
Of course! The 5.5 release is more important than this minor bug. Please, go ahead.

I was just trying to help. Again: how can I enable more debug traces in order to get further insight on whats causing the problem in my side?

**Comment by xgid** [comment]
> the code ... *does* update p.h to the *new* value of s, new_s. 

Yes. What I was trying to say is that in my installation the value of `new_s` after I've changed the **first** placeholder value and pressed `,,` is **always** exactly this one:
```text
@type <|filename|>.md
```
with no regard as to what I've typed for the first placeholder value (which is normally "clean").

My Python 3.5.2 is in fact an Anaconda installation. My intuition is now starting to whisper that this may be the cause... What Python are you using on your side?

**Comment by edreamleo** [comment]
@xgid It's a mystery.  I use Anaconda too.

**Comment by xgid** [comment]
Aha! I have good news! I've tried with this other configuration I had at hand and it has worked!!
```text
Leo Log Window
Leo 5.4, build 20170316064048, Thu Mar 16 06:40:48 CDT 2017
Git repo info: branch = master, commit = bad90a98649f
Python 2.7.12, PyQt version 4.8.6
Windows 10 AMD64 (build 10.0.14393) 
```

So it may be the PyQt version as well. What's yours?

**Comment by edreamleo** [comment]
Works with: Python 3.5.2, PyQt version 5.6.2

Does *not* work with: Python 2.7.12, PyQt version 4.8.7

Both on: Windows 10 AMD64 (build 10.0.14393)

At last I have something to fix :-)

**Comment by technatica** [comment]
Works perfectly for me.


Leo 5.5b1, build 20170317121223, Fri Mar 17 12:12:23 CDT 2017
Git repo info: branch = master, commit = 16002a402953
Python 3.5.2, PyQt version 5.6.0
linux

**Comment by edreamleo** [comment]
@technatica Thanks, Chris, for the confirmation.  It appears this is a Python2/PyQt 4.x bug.

**Comment by edreamleo** [comment]
Fixed at e91464d.  The fix was straightforward.  Finding it took several hours.

Something truly strange just happened. The code worked for me on Python 3 until this morning! There were no recent changes in Leo.  Could a Windows update have broken something?  I doubt that I'll ever figure out what happened. Happily, resolving this mystery is not required.

**Comment by xgid** [comment]
> Fixed at e91464d. The fix was straightforward. Finding it took several hours.

Great! But I'm sorry to say that it's not yet fully working for me... but we are near the end!! Very near! 
Now all the placeholders are being detected and being replaced by the new value I give them, but a comma (`,`) is always being left behind whenever I press `,,` **in the headlines**. This does not happen in the body of any node. That's saying that some minor difference has to be present in the code handling the headlines in respect to the bodies... so we are near.

To make it more clear, after filling in all the placeholders I end up with this tree:
```text
@clean, testfile,.md
	""" The body here """
	Description: a simple test
```

(See the 2 commas in the headline, which should not be there)

Even more: the behaviour of `,,` in the headlines persists even after all the placeholders have been filled in, so whenever I press `,,` again, a comma is left behind.
I have tried the new code with this 3 configurations, with **exactly** the same results:
* Python 2.7.12, PyQt version 4.8.6
* Python 3.5.2, PyQt version 5.6.2
* Python 3.6.0, PyQt version 5.6.2

In all of them, the Python version I'm using is 32bits, even though I have a 64bits Windows 10.

> Something truly strange just happened. The code worked for me on Python 3 until this morning! There were no recent changes in Leo. Could a Windows update have broken something? I doubt that I'll ever figure out what happened. Happily, resolving this mystery is not required.

Let me say that this also happened to me yesterday, but I didn't want to say anything to avoid complicating the issue even more! Briefly after I said that it was working for me with the **Python 2.7.12, PyQt version 4.8.6** combination, it stopped working! And it had nothing to do with Windows updates because I had none, I have checked it out.

The only reason I can think of that may cause this random behaviour would be something related to the specific order in which the Qt events are fired and filtered out by Leo... but this is all speculation. Let's leave it behind if we finally manage to solve the present issue!

**Comment by edreamleo** [comment]
On Sat, Mar 18, 2017 at 5:19 PM, XGiD <notifications@github.com> wrote:

> Fixed at e91464d
> <https://github.com/leo-editor/leo-editor/commit/e91464deb7c0ca1c6abcc058f962b308367d9f27>.
> The fix was straightforward. Finding it took several hours.
>
> Great! But I'm sorry to say that it's not yet fully working for me... but
> we are near the end!! Very near!
> Now all the placeholders are being detected and being replaced by the new
> value I give them, but a comma (,) is always being left behind whenever I
> press ,, *in the headlines*.
>
​Right you are.  Somehow I failed to see the extra comments.  I'll fix this
next.

Edward

**Comment by edreamleo** [comment]
Rev f5955cf seems to fix the latest problem.  Let me know if not.

**Comment by xgid** [comment]
Hi again,

It seems it's still not working perfectly for me. I've found two issues with the present code.
Now the commas are correctly removed and all placeholder values correctly replaced but...:

1. The new value of the last placeholder of a headline **is only correctly shown in the GUI when the focus or edition effectively gets out of that node**. 

Again, I think the best will be an example. With this a new tree abbreviation definition with two nodes, one parent and one child:
```text
mdfile;;
	@<|type|> <|filename|>.md
		""" The body here """
		Description: <|summary|>

		+ This is a child node: <|Main_md_title|>
			""" Body of the child node """
			<|text|>
```

When I set the value for `type` to "clean", it is shown immediately in the GUI. Then I jump to the `filename` field (by pressing `,,`) and fill its value, let's say to `mymdfile`. But as soon as I press `,,` again, the value shown for this field is reverted back to `filename` and the focus jumps to the `summary` field. Then I fill in the summary, and when I press `,,` again **so the focus gets out of this whole node and goes to the child node** the value of the `filename` field is redrawn to the right value I had previously filled in, i.e. `mymdfile`! So during a moment it seems as if the new value had been discarded... but finally it is restored back.
But the same happens with the second node in the expanded abbreviation, the child one. The value I give to the `Main_md_title` placeholder (let's say, `My title`) is ignored when I press `,,`. And in this case it is still wrongly held as `Main_md_title` after I finish filling in the `text` placeholder with its new value and press `,,`, because the focus does not get out of the node at any moment. But, if at this point I save the leo file, the node is redrawn and the value `My title` appears.

This may sound as just a cosmetic issue (a delay in the rendering of the nodes), but there's another error that arises at this moment that seems to indicate that there's a deeper problem beneath. When saving the leo file, this error is shown at the Log pane:
```text
errors writing: C:\proj\code\leo\bugs\mymdfile.md
Orphan node:  My title
parent node: @clean mymdfile.md
not written: mymdfile.md
```

But there's still another issue I have just detected and which seems directly related to all this:
2. I cannot use any of my common abbreviations (the non-tree abbreviations) in the headline of any node. I can use them in the body of any node, but not in the headline.
When I try to use one, for example this one:
```python
f;;={|{x=time.strftime("%Y-%m-%d")}|}
```

as soon as I press the second `;` the focus gets out of the headline and jumps to the body and the first part of the abbreviation name (in this case `f;`) is left behind at the headline, and never replaced by the expected date value.

I'm sorry this issue is getting so hard to be fixed! But I insist **again**: I would like to help in tracing it in order to make this easier for you to get to the root and fix it. Could you please tell me how do you do to activate (and see) the necessary traces for a bug like this one? In other words, which traces may I activate and how? I would **REALLY** like to be able to give you more detailed traces of all the manual tests I do in order to accelerate the bug resolution. I am conscious that there are other **much more important issues** than this one which are needing your immediate attention, so please let me help you as much as I can. May I?

**Comment by edreamleo** [comment]
@xgid I sent you the following via private email.

Almost all the tracing I do is enabled by in each individual method, by a statement that looks like:

    trace = True and not g.unitTesting

Sometimes I want tracing during unit testing. In that case the statement is:

    trace = True and g.unitTesting

Some tracing is enabled via command line arguments, but I hardly ever use that. Regardless of how tracing is enabled, traces are lines like this:

    if trace: g.trace(list of strings)

When I want more detailed control of tracing, I'll define other vars:

    trace = True and not g.unitTesting
    trace_x = True
    trace_y = False
    ...
    if trace and trace_x: g.trace(...)
    ...
    if trace and trace_y: g.trace(...)

The abbreviation code contains many such traces, some recently improved.

**Comment by edreamleo** [comment]
Fixed at a1c1a23. This works for me now.  Not sure why I didn't catch the problem before.

Also not sure why I ever thought calling c.endEditing() was a good idea. Maybe I am forgetting something. Please reopen if necessary.

**Comment by xgid** [comment]
Thanks Eduard!

> @xgid I sent you the following via private email.

Thanks, I've seen it later. I'm now using two email accounts due to the problems I'm facing with GitHub notifications not being sent, so I have a little mess switching from one account to the other and missed your previous email.

By the way, I followed your advice of contacting GitHub's support for that, but have received no answer in 10 days!

Regarding the issue, what I've seen so far with my tests is this:
> 1. The new value of the last placeholder of a headline is only correctly shown in the GUI when the focus or edition effectively gets out of that node.

Solved! It's working like a charm!

> When saving the leo file, this error is shown at the Log pane:
>> errors writing: C:\proj\code\leo\bugs\mymdfile.md
>> Orphan node:  My title
>> parent node: @clean mymdfile.md
>> not written: mymdfile.md

This problem still persists. Maybe it has nothing to do with this current issue?

> 2. I cannot use any of my common abbreviations (the non-tree abbreviations) in the headline of any node.

Solved! Although there's a minor annoying problem which still remains, but I don't know if this can ever be fixed: when the abbreviation is expanded, the focus **always jumps to the body pane**, getting me out of the headline I was editing. So I have to press `Ctrl-h` to get back and go on with the edition.

**Comment by edreamleo** [comment]
@xgid Glad everything works.

> When saving the leo file, this error is shown at the Log pane:

Yes, that is a separate problem.  The `@file` node should have an `@others` directive and/or section reference.

>  when the abbreviation is expanded, the focus always jumps to the body pane.

You could file a separate issue for this, but as you say, it might not be possible to solve.
